"""
PDF Report Builder with Visualizations
Generates comprehensive AI audit reports with charts using ReportLab and Matplotlib
"""

import os
import logging
from datetime import datetime
from typing import Dict, Any, List
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt
import numpy as np
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfgen import canvas

logger = logging.getLogger(__name__)


class PDFBuilder:
    """Builds PDF reports with visualizations for AI audits"""
    
    def __init__(self, output_dir: str = "/tmp"):
        """
        Initialize PDF builder.
        
        Args:
            output_dir: Directory to save generated PDFs
        """
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        
        # Setup styles
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=28,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Normal'],
            fontSize=14,
            textColor=colors.HexColor('#666666'),
            spaceAfter=20,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
        
        # Section header
        self.styles.add(ParagraphStyle(
            name='CustomSectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=12,
            spaceBefore=20,
            fontName='Helvetica-Bold'
        ))
        
        # Body text
        self.styles.add(ParagraphStyle(
            name='CustomBodyText',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#333333'),
            spaceAfter=10,
            alignment=TA_JUSTIFY,
            fontName='Helvetica'
        ))
    
    def create_report(
        self,
        company_data: Dict[str, Any],
        llm_analysis: Dict[str, Any],
        request_id: str
    ) -> str:
        """
        Create complete PDF report.
        
        Args:
            company_data: Company information from webhook
            llm_analysis: Analysis generated by LLM
            request_id: Unique identifier for this request
            
        Returns:
            Path to generated PDF file
        """
        try:
            company_name = company_data.get('company_name', 'Unknown')
            logger.info(f"[{request_id}] Creating PDF for: {company_name}")
            
            # Log what we're working with
            summary = llm_analysis.get('summary', {})
            logger.info(f"[{request_id}] PDF data - Company: {company_name}")
            logger.info(f"[{request_id}] PDF data - Industry: {company_data.get('industry')}")
            logger.info(f"[{request_id}] PDF data - Summary chars: {len(summary.get('personalized_summary', ''))}")
            logger.info(f"[{request_id}] PDF data - Sections: {len(llm_analysis.get('sections', []))}")
            
            # Generate filename
            timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
            company_name_safe = company_name.replace(' ', '_').replace('/', '_')[:30]
            filename = f"AI_Audit_{company_name_safe}_{timestamp}.pdf"
            filepath = os.path.join(self.output_dir, filename)
            
            logger.info(f"[{request_id}] PDF filename: {filename}")
            
            # Create document
            doc = SimpleDocTemplate(
                filepath,
                pagesize=letter,
                rightMargin=0.75*inch,
                leftMargin=0.75*inch,
                topMargin=0.75*inch,
                bottomMargin=0.75*inch
            )
            
            # Build content
            story = []
            
            # Cover page
            story.extend(self._create_cover_page(company_data))
            story.append(PageBreak())
            
            # Executive summary
            story.extend(self._create_executive_summary(company_data, llm_analysis))
            story.append(Spacer(1, 0.3*inch))
            
            # Visualizations
            story.extend(self._create_visualizations(llm_analysis))
            story.append(PageBreak())
            
            # Detailed analysis
            story.extend(self._create_detailed_analysis(llm_analysis))
            
            # Footer
            story.append(PageBreak())
            story.extend(self._create_footer())
            
            # Build PDF
            doc.build(story, onFirstPage=self._add_page_number, onLaterPages=self._add_page_number)
            
            logger.info(f"PDF report generated successfully: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error creating PDF report: {str(e)}", exc_info=True)
            raise
    
    def _create_cover_page(self, company_data: Dict[str, Any]) -> List:
        """Create cover page content"""
        content = []
        
        # Add spacing from top
        content.append(Spacer(1, 1.5*inch))
        
        # Title
        content.append(Paragraph(
            "AI AUDIT REPORT",
            self.styles['CustomTitle']
        ))
        
        content.append(Spacer(1, 0.5*inch))
        
        # Company name
        content.append(Paragraph(
            company_data['company_name'],
            self.styles['Heading1']
        ))
        
        content.append(Spacer(1, 0.3*inch))
        
        # Company details table
        details = [
            ['Industry:', company_data.get('industry', 'N/A')],
            ['Company Size:', company_data.get('company_size', 'N/A')],
            ['Annual Revenue:', company_data.get('annual_revenue_inr', 'N/A')],
            ['Report Date:', datetime.utcnow().strftime('%B %d, %Y')],
            ['Prepared For:', company_data.get('recipient_name', 'N/A')]
        ]
        
        table = Table(details, colWidths=[2*inch, 4*inch])
        table.setStyle(TableStyle([
            ('FONT', (0, 0), (0, -1), 'Helvetica-Bold', 11),
            ('FONT', (1, 0), (1, -1), 'Helvetica', 11),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#333333')),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        
        content.append(table)
        
        return content
    
    def _create_executive_summary(
        self,
        company_data: Dict[str, Any],
        llm_analysis: Dict[str, Any]
    ) -> List:
        """Create executive summary section"""
        content = []
        
        summary = llm_analysis.get('summary', {})
        
        # Section header
        content.append(Paragraph(
            "Executive Summary",
            self.styles['CustomSectionHeader']
        ))
        
        # Personalized summary
        content.append(Paragraph(
            summary.get('personalized_summary', 'No summary available.'),
            self.styles['CustomBodyText']
        ))
        
        content.append(Spacer(1, 0.2*inch))
        
        # Key metrics table
        metrics = [
            ['AI Maturity Level', summary.get('ai_maturity_level', 'N/A')],
            ['Overall Risk Score', f"{summary.get('overall_risk_score', 0)}/100"]
        ]
        
        metrics_table = Table(metrics, colWidths=[2.5*inch, 2*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#3498db')),
            ('BACKGROUND', (1, 0), (1, -1), colors.HexColor('#ecf0f1')),
            ('FONT', (0, 0), (0, -1), 'Helvetica-Bold', 12),
            ('FONT', (1, 0), (1, -1), 'Helvetica-Bold', 12),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
            ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#2c3e50')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.white)
        ]))
        
        content.append(metrics_table)
        
        return content
    
    def _create_visualizations(self, llm_analysis: Dict[str, Any]) -> List:
        """Create visualization charts section"""
        content = []
        
        content.append(Paragraph(
            "AI Readiness Visualization",
            self.styles['CustomSectionHeader']
        ))
        
        sections = llm_analysis.get('sections', [])
        
        if not sections:
            content.append(Paragraph(
                "No department data available for visualization.",
                self.styles['CustomBodyText']
            ))
            return content
        
        # Generate bar chart
        bar_chart_path = self._create_maturity_bar_chart(sections)
        if bar_chart_path:
            img = Image(bar_chart_path, width=6*inch, height=3.5*inch)
            content.append(img)
            content.append(Spacer(1, 0.3*inch))
        
        # Generate radar chart
        radar_chart_path = self._create_risk_radar_chart(sections)
        if radar_chart_path:
            img = Image(radar_chart_path, width=5*inch, height=5*inch)
            content.append(img)
        
        return content
    
    def _create_maturity_bar_chart(self, sections: List[Dict]) -> str:
        """
        Create bar chart showing AI maturity by department.
        
        Args:
            sections: List of department sections from LLM analysis
            
        Returns:
            Path to generated chart image
        """
        try:
            # Extract data
            departments = []
            maturity_scores = []
            colors_list = []
            
            maturity_mapping = {'Low': 30, 'Medium': 60, 'High': 90}
            color_mapping = {'Low': '#e74c3c', 'Medium': '#f39c12', 'High': '#27ae60'}
            
            for section in sections:
                dept_name = section.get('section_name', 'Unknown')
                level = section.get('level', 'Medium')
                
                departments.append(dept_name)
                maturity_scores.append(maturity_mapping.get(level, 50))
                colors_list.append(color_mapping.get(level, '#95a5a6'))
            
            # Create figure
            fig, ax = plt.subplots(figsize=(10, 6))
            
            y_pos = np.arange(len(departments))
            bars = ax.barh(y_pos, maturity_scores, color=colors_list, edgecolor='black', linewidth=1.2)
            
            ax.set_yticks(y_pos)
            ax.set_yticklabels(departments, fontsize=11)
            ax.set_xlabel('AI Maturity Score', fontsize=12, fontweight='bold')
            ax.set_title('Department-wise AI Maturity Levels', fontsize=14, fontweight='bold', pad=20)
            ax.set_xlim(0, 100)
            
            # Add value labels on bars
            for i, (bar, score) in enumerate(zip(bars, maturity_scores)):
                level = list(maturity_mapping.keys())[list(maturity_mapping.values()).index(score)]
                ax.text(score + 2, bar.get_y() + bar.get_height()/2, 
                       f'{level} ({score})', 
                       va='center', fontsize=10, fontweight='bold')
            
            # Grid
            ax.grid(axis='x', alpha=0.3, linestyle='--')
            ax.set_axisbelow(True)
            
            plt.tight_layout()
            
            # Save to file
            chart_path = os.path.join(self.output_dir, 'maturity_bar_chart.png')
            plt.savefig(chart_path, dpi=150, bbox_inches='tight', facecolor='white')
            plt.close()
            
            return chart_path
            
        except Exception as e:
            logger.error(f"Error creating bar chart: {str(e)}")
            return None
    
    def _create_risk_radar_chart(self, sections: List[Dict]) -> str:
        """
        Create radar chart showing department risk distribution.
        
        Args:
            sections: List of department sections from LLM analysis
            
        Returns:
            Path to generated chart image
        """
        try:
            # Extract data
            departments = []
            risk_scores = []
            
            maturity_to_risk = {'Low': 75, 'Medium': 45, 'High': 15}
            
            for section in sections:
                dept_name = section.get('section_name', 'Unknown')
                level = section.get('level', 'Medium')
                
                departments.append(dept_name[:20])  # Truncate long names
                risk_scores.append(maturity_to_risk.get(level, 50))
            
            if len(departments) < 3:
                # Add dummy data for better visualization
                while len(departments) < 4:
                    departments.append(f"Dept {len(departments) + 1}")
                    risk_scores.append(50)
            
            # Number of variables
            num_vars = len(departments)
            
            # Compute angle for each axis
            angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
            risk_scores_plot = risk_scores + [risk_scores[0]]
            angles += angles[:1]
            
            # Create figure
            fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(projection='polar'))
            
            # Plot data
            ax.plot(angles, risk_scores_plot, 'o-', linewidth=2, color='#e74c3c', label='Risk Level')
            ax.fill(angles, risk_scores_plot, alpha=0.25, color='#e74c3c')
            
            # Fix axis to go in the right order
            ax.set_theta_offset(np.pi / 2)
            ax.set_theta_direction(-1)
            
            # Set labels
            ax.set_xticks(angles[:-1])
            ax.set_xticklabels(departments, fontsize=10)
            
            # Set y-axis limits
            ax.set_ylim(0, 100)
            ax.set_yticks([25, 50, 75, 100])
            ax.set_yticklabels(['25', '50', '75', '100'], fontsize=8, color='gray')
            
            # Add title
            ax.set_title('Risk Distribution Across Departments', 
                        fontsize=14, fontweight='bold', pad=20)
            
            # Grid styling
            ax.grid(True, linestyle='--', alpha=0.7)
            
            plt.tight_layout()
            
            # Save to file
            chart_path = os.path.join(self.output_dir, 'risk_radar_chart.png')
            plt.savefig(chart_path, dpi=150, bbox_inches='tight', facecolor='white')
            plt.close()
            
            return chart_path
            
        except Exception as e:
            logger.error(f"Error creating radar chart: {str(e)}")
            return None
    
    def _create_detailed_analysis(self, llm_analysis: Dict[str, Any]) -> List:
        """Create detailed department-wise analysis"""
        content = []
        
        content.append(Paragraph(
            "Detailed Department Analysis",
            self.styles['CustomSectionHeader']
        ))
        
        content.append(Paragraph(
            "The following sections highlight specific drawbacks and limitations identified in each department:",
            self.styles['CustomBodyText']
        ))
        
        content.append(Spacer(1, 0.2*inch))
        
        sections = llm_analysis.get('sections', [])
        
        for section in sections:
            dept_name = section.get('section_name', 'Unknown Department')
            level = section.get('level', 'N/A')
            drawbacks = section.get('drawbacks', [])
            
            # Department header
            content.append(Paragraph(
                f"{dept_name} (Maturity: {level})",
                self.styles['Heading3']
            ))
            
            if not drawbacks:
                content.append(Paragraph(
                    "No significant drawbacks identified. This department demonstrates good AI maturity.",
                    self.styles['CustomBodyText']
                ))
            else:
                # Create drawbacks list
                for i, drawback in enumerate(drawbacks, 1):
                    title = drawback.get('title', 'Unnamed Issue')
                    details = drawback.get('details', 'No details provided.')
                    
                    content.append(Paragraph(
                        f"<b>{i}. {title}</b>",
                        self.styles['CustomBodyText']
                    ))
                    
                    content.append(Paragraph(
                        details,
                        self.styles['CustomBodyText']
                    ))
                    
                    content.append(Spacer(1, 0.1*inch))
            
            content.append(Spacer(1, 0.2*inch))
        
        return content
    
    def _create_footer(self) -> List:
        """Create footer section"""
        content = []
        
        content.append(Spacer(1, 1*inch))
        
        footer_style = ParagraphStyle(
            name='Footer',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#7f8c8d'),
            alignment=TA_CENTER
        )
        
        content.append(Paragraph(
            "━" * 80,
            footer_style
        ))
        
        content.append(Spacer(1, 0.1*inch))
        
        content.append(Paragraph(
            "<b>Generated by AI Audit Agent</b>",
            footer_style
        ))
        
        content.append(Paragraph(
            "Confidential Document | For Internal Use Only",
            footer_style
        ))
        
        content.append(Paragraph(
            f"Generated on {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}",
            footer_style
        ))
        
        return content
    
    def _add_page_number(self, canvas, doc):
        """Add page numbers to each page"""
        page_num = canvas.getPageNumber()
        text = f"Page {page_num}"
        canvas.saveState()
        canvas.setFont('Helvetica', 9)
        canvas.setFillColor(colors.HexColor('#7f8c8d'))
        canvas.drawRightString(7.5*inch, 0.5*inch, text)
        canvas.restoreState()
